### ISSUE TITLE
Unable to press <left> to return to page 1 of results when the top entry of the page is highlighted

### ISSUE THREAD

**Issue by Szeraax** [ieviev/pscomplete#1]
Using Pwsh 7.2 (I know, I need to update!), I can press right to advance all pages. But if I am currently highlighting the top entry in the list, I cannot press left to go back to the first page. If I'm on the 2nd from top entry, I can press left to get to the first page. The bottom entry highlighted works fine for going back to the 1st page as well.

**Comment by ieviev** [comment]
It's probably an off by one error, can you return from the second entry?

I'll look into it soon

Edit: ok that was in the question.

yeah i'll fix it soon

**Comment by Szeraax** [comment]
Yes

**Comment by ieviev** [comment]
fixed in 0.0.10
