### ISSUE TITLE
I have a issue when i run import-module pscomplete

### ISSUE THREAD

**Issue by LuuKhoaHoc** [ieviev/pscomplete#3]
Im using window 11, pwsh v7.3.7,  PSRealine 2.2.6

**Comment by LuuKhoaHoc** [comment]
Import-Module: Could not load file or assembly 'C:\Users\<User-Name>\Documents\PowerShell\Modules\PScomplete\0.0.21\FSharp.Core.dll'.
Format of the executable (.exe) or library (.dll) is invalid.
Import-Module: A BadImageFormatException has been thrown while parsing the signature. This is likely due to lack of a generic context.
Ensure genericTypeArguments and genericMethodArguments are provided and contain enough context.

**Comment by ieviev** [comment]
ah, it's using netstandard2.1 instead of 2.0, i'll release a new version soon - you can use version 0.0.19 for now
